CREATE TABLE IF NOT EXISTS signal_mfe_analysis (
  signal_id UUID PRIMARY KEY,
  symbol TEXT NOT NULL,
  candle_time TIMESTAMPTZ NOT NULL,
  entry_price NUMERIC NOT NULL,
  stop_loss NUMERIC NOT NULL,
  risk_per_unit NUMERIC NOT NULL,
  regime_production TEXT,
  price_15m NUMERIC,
  price_30m NUMERIC,
  price_1h NUMERIC,
  price_2h NUMERIC,
  price_4h NUMERIC,
  mfe_15m NUMERIC, mae_15m NUMERIC,
  mfe_30m NUMERIC, mae_30m NUMERIC,
  mfe_1h NUMERIC,  mae_1h NUMERIC,
  mfe_2h NUMERIC,  mae_2h NUMERIC,
  mfe_4h NUMERIC,  mae_4h NUMERIC,
  time_to_03r_min NUMERIC,
  time_to_05r_min NUMERIC,
  time_to_07r_min NUMERIC,
  time_to_1r_min NUMERIC,
  strategy_a_r NUMERIC,
  strategy_b_r NUMERIC,
  strategy_c_r NUMERIC,
  strategy_d_r NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
